export default {
  SET_PROJECTS_DATA: 'SET_PROJECTS_DATA',
  SET_IS_PROJECTS_CHANGED: 'SET_IS_PROJECTS_CHANGED',
  SET_BALANCE_DATA: 'SET_BALANCE_DATA',
  SET_IS_BALANCE_CHANGED: 'SET_IS_BALANCE_CHANGED',
  SET_TRANSACTION_DATA: 'SET_TRANSACTION_DATA',
  SET_IS_TRANSACTION_CHANGED: 'SET_IS_TRANSACTION_CHANGED',
};
